name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
    ## Hva er nytt?

    $CHANGES
categories:
    - title: '🧶 Avhengighetsoppdateringer'
      label: 'dependencies'
