apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
    name: su-se-framover
    namespace: supstonad
    labels:
        team: supstonad
spec:
    groups:
        - name: su-se-framover
          rules:
              - alert: su-se-framover-ingress-utilgjengelig
                expr: sum(up{app="su-se-framover", namespace="supstonad", job=~"probe/.*", k8s_cluster_name="{{K8S_CLUSTER_NAME}}"}) < 1
                for: 1m
                annotations:
                    consequence: 'su-se-framover sin ingress har vært utilgjengelig i minst 1 minutt'
                    action: '`kubectl describe deployment su-se-framover -n supstonad` for events, og `kubectl logs -l app=su-se-framover -n supstonad` for logger'
                labels:
                    namespace: supstonad
                    severity: critical
              - alert: su-se-framover-error-logg
                expr:
                    'sum_over_time(loki:service:loglevel:count1m{service_name="su-se-framover",service_namespace="supstonad",k8s_cluster_name="{{K8S_CLUSTER_NAME}}",detected_level="error"}[15m:1m]) > 0'
                for: 1s
                annotations:
                    consequence: 'su-se-framover har fått error i loggen siste 15 min'
                    action: 'Det er logget en melding med log level ERROR. Sjekk logger her: `{{LOGS_URL_LOKI}}`'
                labels:
                    namespace: supstonad
                    severity: critical
              - alert: su-se-framover-pods-available
                expr: (sum(kube_deployment_status_replicas_available{deployment="su-se-framover", k8s_cluster_name="{{K8S_CLUSTER_NAME}}"}) or vector(0)) < 1
                for: 1m
                annotations:
                    consequence: 'Tilgjengelige kubernetes pods for su-se-framover er mindre enn 1'
                    action: '`kubectl describe deployment su-se-framover -n supstonad` for events, og `kubectl get pods -l app=su-se-framover -n supstonad` for pods'
                labels:
                    namespace: supstonad
                    severity: critical
