apiVersion: nais.io/v1alpha1
kind: Application
metadata:
   name: su-se-framover
   namespace: default
   labels:
      team: supstonad
spec:
   port: 80
   image: {{ image }}
   replicas:
      min: 1
   liveness:
      path: isalive
      port: 8080
   readiness:
      path: isready
      port: 8080
   ingresses:
      - {{ingress}}
   env:
      {{#each env}}
       - name: {{@key}}
         value: "{{this}}"
      {{/each}}