apiVersion: nais.io/v1alpha1
kind: Application
metadata:
   name: su-se-framover
   namespace: supstonad
   labels:
      team: supstonad
spec:
   port: 80
   image: {{ image }}
   azure:
      application:
          enabled: true
   replicas:
      min: 1
   liveness:
      path: isAlive
      port: 80
   readiness:
      path: isReady
      port: 80
   ingresses:
      - {{ingress}}
   env:
      {{#each env}}
       - name: {{@key}}
         value: "{{this}}"
      {{/each}}
