apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: su-se-framover
  namespace: supstonad
  labels:
    team: supstonad
spec:
  port: 8080
  image: {{ image }}
  azure:
    application:
      enabled: true
      tenant: {{ tenant }}
      claims:
        extra:
          - "NAVident"
        groups:
          - id: {{ env.AZURE_GROUP_ATTESTANT }}
          - id: {{ env.AZURE_GROUP_SAKSBEHANDLER }}
          - id: {{ env.AZURE_GROUP_VEILEDER }}
          - id: {{ env.AZURE_GROUP_DRIFT }}
      replyURLs:
        - "http://localhost/oauth2/callback"
        - "{{ingress}}/oauth2/callback"
  webproxy: true
  replicas:
    min: 2
  liveness:
    path: isAlive
    port: 8080
  readiness:
    path: isReady
    port: 8080
  ingresses:
    - {{ingress}}
  vault:
    enabled: true
  env:
    {{#each env}}
      - name: {{@key}}
        value: "{{this}}"
    {{/each}}
      - name: NODE_ENV
        value: production
      - name: REDIS_HOST
        value: su-se-framover-redis
      - name: SU_SE_BAKOVER_URL
        value: http://su-se-bakover
  envFrom:
    - secret: redis-password
---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: supstonad
  name: su-se-framover-redis
  namespace: supstonad
spec:
  image: bitnami/redis:6.0
  port: 6379
  replicas: # A single Redis-app doesn't scale
    min: 1
    max: 1 # More replicas doesn't sync
  resources: # you need to monitor the resource usage yourself
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 6379
    protocol: redis
  envFrom:
    - secret: redis-password
  env:
    - name: REDIS_TMP_DIR
      value: "/tmp/redis"
