apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
  name: su-se-framover
  namespace: supstonad
  labels:
    team: supstonad
spec:
  port: 8080
  image: {{ image }}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "b64af061-f7c4-4d05-907f-b457e23da339" # 0000-GA-SU-UFOR-ATTESTANT
          - id: "654d28c0-b02b-4c50-86a0-896cf64e79f0" # 0000-GA-SU-UFOR-SAKSBEHANDLER
          - id: "4b1ccffd-b1e1-41a7-9f3a-d4acb6d53b05" # 0000-GA-SU-UFOR-VEILEDER
          - id: "6c5cb261-d91e-40a8-a925-458bfdd9d033" # 0000-GA-SU-UFOR-DRIFT
      replyURLs:
        - "http://localhost/oauth2/callback"
        - "https://supplerendestonad.nais.adeo.no/oauth2/callback"
        - "https://supplerendestonad.intern.nav.no/oauth2/callback"
  webproxy: true
  replicas:
    min: 2
  liveness:
    path: isAlive
    port: 8080
    initialDelay: 5
  readiness:
    path: isReady
    port: 8080
    initialDelay: 5
  ingresses:
    - https://supplerendestonad.nais.adeo.no
    - https://supplerendestonad.intern.nav.no
  vault:
    enabled: true
  env:
      - name: NODE_ENV
        value: production
      - name: REDIS_HOST
        value: su-se-framover-redis
      - name: SU_SE_BAKOVER_URL
        value: http://su-se-bakover
      - name: NPM_CONFIG_CACHE
        value: /tmp
      - name: AZURE_GROUP_ATTESTANT
        value: "b64af061-f7c4-4d05-907f-b457e23da339"
      - name: AZURE_GROUP_VEILEDER
        value: "4b1ccffd-b1e1-41a7-9f3a-d4acb6d53b05"
      - name: AZURE_GROUP_SAKSBEHANDLER
        value: "654d28c0-b02b-4c50-86a0-896cf64e79f0"
      - name: AZURE_GROUP_DRIFT
        value: "6c5cb261-d91e-40a8-a925-458bfdd9d033"
      - name: SU_SE_BAKOVER_AAD_APP_NAME
        value: "prod-fss.supstonad.su-se-bakover"
      - name: AUTH_LOGIN_REDIRECT_URI
        value: "https://supplerendestonad.intern.nav.no/oauth2/callback"
      - name: AUTH_LOGOUT_REDIRECT_URI
        value: "https://supplerendestonad.intern.nav.no/"
  envFrom:
    - secret: redis-password
    - secret: su-se-framover-session-key
---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: supstonad
  name: su-se-framover-redis
  namespace: supstonad
  annotations:
    nais.io/run-as-group: "0" # Fix permissions for bitnami/redis
    nais.io/read-only-file-system: "false" # Fix permissions for bitnami/redis
spec:
  image: bitnami/redis:6.0
  port: 6379
  replicas: # A single Redis-app doesn't scale
    min: 1
    max: 1 # More replicas doesn't sync
  resources: # you need to monitor the resource usage yourself
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 6379
    protocol: redis
  envFrom:
    - secret: redis-password
