export default {
    'input.sats.label': 'Sats',
    'input.sats.value.høy': 'Høy',
    'input.sats.value.lav': 'Lav',
    'knapp.startBeregning': 'Start beregning',
    'knapp.neste': 'Neste',
    'datovelger.fom.label': 'Startdato',
    'datovelger.tom.label': 'Sluttdato',
    'feiloppsummering.title': 'For å gå videre må du rette opp følgende:',
    'utbetaling.tabellheader.beløp': 'Beløp',
    'utbetaling.tabellheader.grunnbeløp': 'Grunnbeløp',
    'fradrag.heading': 'Fradrag',
    'input.fradragstype.label': 'Type',
    'input.fradragsbeløp.label': 'Beløp per år',
    'input.fradragsbeskrivelse.label': 'Beskrivelse',
    'knapp.fradrag.leggtil': 'Legg til fradrag',
    'knapp.fradrag.fjern': 'Fjern fradrag',
    'input.fradragstype.emptyLabel': 'Velg fradragstype',
    'fradrag.type.uføre': 'Uføretrygd',
    'fradrag.type.barnetillegg': 'Barnetillegg',
    'fradrag.type.arbeidsinntekt': 'Arbeidsinntekt',
    'fradrag.type.pensjon': 'Pensjon',
    'fradrag.type.kapitalinntekt': 'Kapitalinntekt',
    'fradrag.type.andreytelser': 'Andre ytelser',
};
