export default {
    'beregning.forventerArbeidsinntekt': 'Forventer du å ha arbeidsinntekt fremover?',
    'beregning.andreYtelserINav': 'Har du andre ytelser i NAV?',
    'beregning.sømtOmAndreTrygdeytelser': 'Har du søkt om andre trygdeytelser som ikke er behandlet?',
    'beregning.mottattSosialstønadSiste3måneder': 'Har du mottatt sosialstønad i løpet av de siste tre måneder?',
    'beregning.trygdeytelserIUtlandet': 'Har du trygdeytelser i utlandet?',
    'beregning.tjenestepensjon/pensjonssparing': 'Har du tjenestepensjon og/eller pensjonssparing?',

    'beregning.es': 'Ektefelle/samboer (E/S)',
    'beregning.es.forventerArbeidsinntekt': 'Forventer ektefelle/samboer å ha arbeidsinntekt fremover?',
    'beregning.es.andreYtelserINav': 'Har ektefelle/samboer andre ytelser i NAV?',
    'beregning.es.sømtOmAndreTrygdeytelser': 'Har ektefelle/samboer søkt om andre trygdeytelser som ikke er behandlet?',
    'beregning.es.mottattSosialstønadSiste3måneder':
        'Har ektefelle/samboer mottatt sosialstønad i løpet av de siste tre måneder?',
    'beregning.es.trygdeytelserIUtlandet': 'Har ektefelle/samboer trygdeytelser i utlandet?',
    'beregning.es.tjenestepensjon/pensjonssparing': 'Har ektefelle/samboer tjenestepensjon og/eller pensjonssparing?',

    'display.fraSøknad': 'Fra søknad',
    'display.fraSaksbehandling': 'Fra saksbehandling',
    'display.ikkeVurdert': 'Ikke vurdert',

    'fastOpphold.adresse': 'Adresse',
    'fastOpphold.erNorskStatsborger': 'Er søker norsk statsborger?',
    'fastOpphold.harOppholdstillatelse': 'Har oppholdstillatelse?',
    'fastOpphold.typeOppholdstillatelse': 'Type oppholdstillatelse',

    'flyktning.registrertFlyktning': 'Er du registrert flyktning?',

    'formue.tittel': 'Formue',
    'formue.heading.søker': 'Søker',
    'formue.heading.eps': 'Ektefelle/samboer',
    'formue.delerBoligMed': 'Hvem deler du bolig med?',
    'formue.ektefelleTitle': 'Ektefelle',
    'formue.epsFnr': 'Ektefelles fødselsnummer',
    'formue.ektefellesNavn': 'Ektefelles navn (hvis oppgitt)',
    'formue.ektefellesFormue': 'Ektefelles totale formue',
    'formue.verdiPåBolig': 'Verdi på bolig',
    'formue.verdiPåEiendom': 'Verdi på eiendom',
    'formue.verdiPåKjøretøy': 'Verdi på Kjøretøy',
    'formue.innskuddsbeløp': 'Innskuddsbeløp',
    'formue.verdipapirbeløp': 'Verdipapirbeløp',
    'formue.kontanter': 'Kontanter over 5000',
    'formue.skylderNoenSøkerPengerBeløp': 'Skylder noen søker penger',
    'formue.depositumsBeløp': 'Depositumskonto',
    'formue.totalt': 'Totalt',

    'formue.ektefelle.verdiPåBolig': 'Ektefelles verdi på bolig',
    'formue.ektefelle.verdiPåEiendom': 'Ektefelles verdi på eiendom',
    'formue.ektefelle.verdiPåKjøretøy': 'Ektefelles verdi på kjøretøy',
    'formue.ektefelle.innskuddsbeløp': 'Ektefelles innskuddsbeløp',
    'formue.ektefelle.verdipapirbeløp': 'Ektefelles verdipapirbeløp',
    'formue.ektefelle.kontanter': 'Ektefelles kontanter (kun over 5000)',
    'formue.ektefelle.skylderNoenEktefellePengerBeløp': 'Skylder noen ektefelle penger',
    'formue.ektefelle.depositumsBeløp': 'Ektefelles depositumskonto',

    'fraSøknad.ja': 'Ja',
    'fraSøknad.nei': 'Nei',
    'fraSøknad.uavklart': 'Uavklart',
    'fraSøknad.ikkeRegistert': 'Ikke registert fra søknad',

    'sats.tittel': 'Sats',
    'sats.harOppholdstillatelse': 'Har oppholdstillatelse?',
    'sats.hvemDelerSøkerBoligMed': 'Hvem deler søker bolig med?',
    'sats.hvemDelerSøkerBoligMed.ingen': 'Ingen',
    'sats.ektemakeEllerSamboerUførFlyktning': 'Mottar ektemake eller samboer supplerende stønad for uføre flyktninger?',

    'personligOppmøte.hvemHarMøtt': 'Hvem har møtt opp?',
    'personligOppmøte.personligOppmøte': 'Personlig',
    'personligOppmøte.papirsøknad.grunnForPapirinnsending': 'Grunn for papirinnsending',
    'personligOppmøte.papirsøknad.vergeSøktPåVegneAvBruker': 'Verge har søkt på vegne av bruker',
    'personligOppmøte.papirsøknad.midlertidigUnntakForOppmøteplikt': 'Midlertidig unntak for oppmøteplikt',

    'uførhet.vedtakOmUføretrygd': 'Har du fått vedtak om uføretrygd?',

    'utenlandsOpphold.antallDagerSiste90': 'Antall dager oppholdt i utlandet siste 90 dager',
    'utenlandsOpphold.antallDagerPlanlagt': 'Antall dager planlagt opphold i utlandet',
    'utenlandsOpphold.datoerSiste90': 'Datoer for opphold i siste 90 dager',
    'utenlandsOpphold.datoerPlanlagt': 'Planlagt opphold i utlandet',
    'utenlandsOpphold.ikkeRegistert': 'Det er ikke registert noen datoer',
    'utenlandsOpphold.utreisedato': 'Det er ikke registert noen datoer',
    'utenlandsOpphold.innreisedato': 'Det er ikke registert noen datoer',

    'bosituasjon.vurderingAvSats': 'Vurdering av sats',
    'bosituasjon.sats.høy': 'Høy',
    'bosituasjon.sats.ordinær': 'Ordinær',
};
