export default {
    'input.opphold-i-norge.label': 'Bor og oppholder du deg i Norge?',
    'input.folkereg-adresse.label': 'Bor på folkereg adresse?',
    'input.delerBoligMedPersonOver18.label': 'Deler du bolig med noen over 18 år?',
    'input.delerBoligMed.label': 'Hvem deler du bolig med?',
    'input.delerBoligMedEktefelleEllerSamboer.label': 'Ektefelle eller samboer',
    'input.delerBoligMedBarnOver18.label': 'Voksne barn',
    'input.delerBoligMedAndreVoksne.label': 'Andre voksne',
    'input.ektefelleEllerSamboerFnr.label': 'Hva er fødselsnummeret til ektefelle eller samboer?',
    'input.ektefelleEllerSamboerFnrDescription.label': '11 siffer',
    'input.ektefelleEllerSamboerNavn.label': 'Hva er navnet til ektefelle eller samboer?',
    'input.ektefelleEllerSamboerFødselsdato.label': 'Hva er fødselsdatoen til ektefelle eller samboer?',
    'input.ektefelleEllerSamboerUnder67År.label': 'Er ektefelle eller samboer under 67 år?',
    'input.ektefelleEllerSamboerUførFlyktning.label': 'Er ektefelle eller samboer ufør flyktning?',
};
