export default {
    'input.harForventetInntekt.label': 'Forventer du å ha arbeidsinntekt fremover?',
    'input.forventetInntekt.label': 'Forventet arbeidsinntekt i kroner per måned',
    'hjelpetekst.harForventetInntekt.body': 'Gjelder all inntekt i Norge og utlandet.',
    'input.mottarPensjon.label': 'Mottar du tjenestepensjon eller pensjon?',
    'input.pensjonsOrdning.label': 'Pensjonsgiver',
    'input.pensjonsBeløp.label': 'Beløp per måned',
    'input.harMottattSosialstønad.label': 'Har du mottatt sosialstønad i løpet av de siste tre månedene?',
    'input.sosialStønadBeløp.label': 'Beløp i kroner for alle tre månedene',
    'input.trygdeytelserIUtlandet.label': 'Har du trygdeytelser i utlandet?',
    'input.trygdeytelserIUtlandetBeløp.label': 'Brutto beløp i lokal valuta per år',
    'input.trygdeytelserIUtlandetType.label': 'Ytelse',
    'input.trygdeytelserIUtlandetFra.label': 'Hvem gir ytelsen?',
    'input.andreYtelserINAV.label': 'Har du andre ytelser i NAV?',
    'input.andreYtelserINavYtelse.label': 'Hvilke ytelser?',
    'input.andreYtelserINavBeløp.label': 'Beløp i kroner per måned',
    'input.søktAndreYtelserIkkeBehandlet.label': 'Har du søkt om andre trygdeytelser som ikke er behandlet?',
    'input.søktAndreYtelserIkkeBehandletBegrunnelse.label': 'Hvilke? ',

    'button.fjernRad.label': 'Fjern rad',
    'button.leggTil.label': 'Legg til',
};
