export const FETCH_SAKSOVERSIKT = 'FETCH_SAKSOVERSIKT';
export const SAKSOVERSIKT_SUBMIT = 'SAKSOVERSIKT_SUBMIT';
export const KONTROLLSAMTALE_UPDATED = 'KONTROLLSAMTALE_UPDATED';
export const UTBETALING_UPDATED = 'UTBETALING_UPDATED';
export const SAKSNOTATER_UPDATED = 'SAKSNOTATER_UPDATED';
export const HENDELSE_UPDATED = 'HENDELSE_UPDATED';
