export default {
    'oppsummering.endreSvar': 'Endre svar',

    'panel.tittel.uførevedtak': 'Uførevedtak',
    'input.uførevedtak.label': 'Har du uførevedtak?',

    'panel.tittel.flyktningstatus': 'Flyktningstatus',
    'input.flyktning.label': 'Er du registrert som flyktning?',
    'input.norsk.statsborger.label': 'Er du norsk statsborger?',
    'input.oppholdstillatelse.label': 'Har du oppholdstillatelse i Norge?',
    'input.hvilken.oppholdstillatelse.label': 'Hvilken type oppholdstillatelse har du?',
    'input.permanent.oppholdstillatelse.label': 'Permanent',
    'input.midlertidig.oppholdstillatelse.label': 'Midlertidig',
    'input.midlertidig.oppholdstillatelse.opphører.label':
        'Er det mindre enn tre måneder til oppholdstillatelsen opphører?',
    'input.oppholdtillatelse.forlengelse.label': 'Har du søkt forlengelse?',
    'input.statsborger.andre.land.label': 'Har du statsborgerskap i andre land enn Norge?',
    'input.statsborger.andre.land.fritekst.label': 'Hvilke land?',

    'panel.tittel.boOgOpphold': 'Bo og opphold i Norge',
    'input.opphold-i-norge.label': 'Bor og oppholder i Norge?',
    'input.folkereg-adresse.label': 'Bor på folkereg adresse?',
    'input.delerBoligMedPersonOver18.label': 'Deler du bolig med noen over 18 år?',
    'input.delerBoligMed.label': 'Hvem deler du bolig med?',
    'input.delerBoligMedEktemakeEllerSamboer.label': 'Ektemake eller samboer',
    'input.delerBoligMedBarnOver18.label': 'Voksne barn',
    'input.delerBoligMedAndreVoksne.label': 'Andre voksne',
    'input.ektemakeEllerSamboerFnr.label': 'Fødselsnummer eller fødselsdato på ektefelle eller samboer?',
    'input.ektemakeEllerSamboerUførFlyktning.label': 'Er ektefelle eller samboer ufør flyktning?',

    'panel.tittel.dinFormue': 'Din formue',

    'panel.tittel.dinInntekt': 'Din inntekt',
    'panel.tittel.ektefelle.inntekt': 'Ektefelles inntekt',
    'input.harForventetInntekt.label': 'Forventer du å ha arbeidsinntekt fremover?',
    'input.forventetInntekt.label': 'Forventet arbeidsinntekt i kroner per måned',
    'input.mottarPensjon.label': 'Har du tjenestepensjon og/eller pensjonssparing?',
    'input.pensjonsOrdning.label': 'Pensjonsgiver',
    'input.pensjonsBeløp.label': 'Beløp per måned',
    'input.harMottattSosialstønad.label': 'Har du mottatt sosialstønad i løpet av de siste tre månedene?',
    'input.sosialStønadBeløp.label': 'Beløp i kroner for alle tre månedene',
    'input.trygdeytelserIUtlandet.label': 'Har du trygdeytelser i utlandet?',
    'input.trygdeytelserIUtlandetBeløp.label': 'Beløp i kroner per måned',
    'input.trygdeytelserIUtlandetType.label': 'Hvilken ytelser?',
    'input.trygdeytelserIUtlandetFraHvem.label': 'Hvem gir disse ytelsene?',
    'input.tjenerPengerIUtlandet.label': 'Tjener du penger i utlandet?',
    'input.tjenerPengerIUtlandetBeløp.label': 'Beløp i kroner per måned',
    'input.andreYtelserINAV.label': 'Har du andre ytelser i NAV?',
    'input.andreYtelserINavYtelse.label': 'Hvilken ytelser?',
    'input.andreYtelserINavBeløp.label': 'Beløp i kroner per måned',
    'input.søktAndreYtelserIkkeBehandlet.label': 'Har du søkt om andre trygdeytelser som ikke er behandlet?',
    'input.søktAndreYtelserIkkeBehandletBegrunnelse.label': 'Hvilke? ',

    'panel.tittel.ektefellesFormue': 'Ektefelle/samboers formue',

    'panel.tittel.reiseTilUtlandet': 'Reise til utlandet',
    'input.harReistSiste90.label': 'Har du reist til utlandet de siste 90 dager?',
    'input.skalReiseNeste12.label': 'Har du planer om å reise til utlandet i de neste 12 månedene?',
    'input.utreisedato': 'Utreisedato',
    'input.innreisedato': 'innreisedato',

    'panel.tittel.forVeileder': 'forVeileder',
};
