export default {
    'skattegrunnlag.fnr': 'Fødselsnummer',
    'skattegrunnlag.tidspunktHentet': 'Tidspunkt hentet',

    'årsgrunnlag.inntektsår': 'Inntektsår',
    'årsgrunnlag.stadie': 'Stadie',
    'årsgrunnlag.skatteoppgjørsdato': 'Skatteoppgjørsdato',
    'årsgrunnlag.skatteoppgjørsdato.finnesIkke': 'Skatteoppgjørsdato finnes ikke',

    'grunnlagstype.formue': 'Formue',
    'grunnlagstype.inntekt': 'Inntekt',
    'grunnlagstype.inntektsfradrag': 'Inntektsfradrag',
    'grunnlagstype.formuesfradrag': 'Formuesfradrag',
    'grunnlagstype.verdsettingsrabattSomGirGjeldsreduksjon': 'VerdsettingsrabattSomGirGjeldsreduksjon',
    'grunnlagstype.oppjusteringAvEierinntekter': 'OppjusteringAvEierinntekter',
    'grunnlagstype.annet': 'Annet',

    'kjøretøySpesifisering.antattMarkedsverdi': 'Antatt markedsverdi',
    'kjøretøySpesifisering.antattVerdiSomNytt': 'Antatt verdi som nytt',
    'kjøretøySpesifisering.beløp': 'Beløp',
    'kjøretøySpesifisering.fabrikatnavn': 'Fabrikatnavn',
    'kjøretøySpesifisering.formuesverdi': 'Formuesverdi',
    'kjøretøySpesifisering.registreringsnummer': 'Registreringsnummer',
    'kjøretøySpesifisering.årForFørstegangsregistrering': 'År for førstegangsregistrering',
    'kjøretøySpesifisering.verdiFinnesIkke': 'Verdi finnes ikke',

    'seSkattegrunnlag.knapp.seSkatt': 'Se skattegrunnlag',
    'seSkattegrunnlag.modal.tittel': 'Skattegrunnlag',

    // Oversettelser for tekniskNavn
    aarsavgiftForKontoIVerdipapirregister: 'Årsavgift VPS konto',
    alderspensjonFraIPAOgIPS: 'Alderspensjon fra individuell pensjonsordning (IPS/IPA)',
    alminneligInntektFoerSaerfradrag: 'Alminnelig inntekt før særfradrag',
    andelAvFellesgjeldISDF: 'Andel av netto gjeld i selskap med deltakerfastsetting',
    andelAvUnderskuddFraTidligereAarVedDriftAvVaaningshusSomAnvendesIAaret:
        'Underskudd fra tidligere års drift av våningshus',
    andelIFellesTapVedSalgAvAndelISDF: 'Andel av tap ved salg mv. av andel i selskap med deltakerfastsetting',
    andelIFellesTilleggIAlminneligInntektFraSDFInnenAnnenNaering:
        'Tillegg i alminnelig inntekt fra selskap med deltakerfastsetting',
    andelIFellesTilleggIAlminneligInntektFraSDFInnenBarnepassIBarnepasserensHjem:
        'Tillegg i alminnelig inntekt fra selskap med deltakerfastsetting innen fiske eller familiebarnehage',
    andreFradragsberettigedeKostnader: 'Andre fradrag',
    annenArbeidsinntekt: 'Annen arbeidsinntekt',
    annenGjeld: 'Annen gjeld',
    annenPensjonFoerAlderspensjon: 'Annen pensjon før alderspensjon',
    annenSkattepliktigKapitalinntektFraAnnetFinansprodukt:
        'Annen skattepliktig kapitalinntekt fra andre finansprodukter',
    annenSkattepliktigKapitalinntektFraVirtuellValuta:
        'Annen skattepliktig kapitalinntekt fra virtuell valuta / kryptovaluta',
    arbeidsavklaringspenger: 'Arbeidsavklaringspenger',
    arbeidsinntektFraKompensasjonsytelseUtbetaltAvNav: 'Lønnsinntekt av kompensasjon fra NAV',
    avkortetFordelVedElektroniskKommunikasjon: 'Fordel elektronisk kommunikasjon',
    barnepensjonFraAndreEnnFolketrygden: 'Barnepensjon fra andre enn folketrygden',
    barnepensjonFraFolketrygden: 'Barnepensjon fra folketrygden',
    barnepensjonFraIPAOgIPS: 'Barnepensjon fra individuell pensjonsordning (IPS/IPA)',
    bruttoformue: 'Bruttoformue',
    dagpengerForNaeringsdrivendeOgFisker: 'Dagpenger for næringsdrivende herunder fiskere',
    dagpengerVedSykehusoppholdMvFraBarneforsikring: 'Dagpenger fra barneforsikring',
    ektefelletilleggTilPensjon: 'Ektefelletillegg til pensjon',
    ektefelletilleggTilUfoeretrygd: 'Ektefelletillegg til uføretrygd',
    engangsutbetalingFraIPSIPA: 'Engangsutbetaling fra individuell pensjonsordning (IPS/IPA)',
    etterlattepensjonFraFolketrygden: 'Gjenlevendepensjon og overgangsstønad til gjenlevende',
    formuesverdiAvUtestaaendeFordring: 'Andre krav/fordringer',
    formuesverdiForAndelIRentedelIVerdipapirfond: 'Verdipapirfond - rentedel',
    formuesverdiForAnnenFastEiendom: 'Annen fast eiendom',
    formuesverdiForAnnenFastEiendomInnenforInntektsgivendeAktivitet:
        'Annen fast eiendom innenfor inntektsgivende aktivitet',
    formuesverdiForAnnetFinansprodukt: 'Andre finansprodukter',
    formuesverdiForBorett: 'Borett',
    formuesverdiForBuskap: 'Buskap',
    formuesverdiForEgenFritaksbehandletBolig: 'Egen fritaksbehandlet bolig',
    formuesverdiForFormuesobjekterINaeringIkkeOmfattetAvVerdsettingsrabatt: 'Annen formue fra næringsvirksomhet',
    formuesverdiForFritidsbaatMedSalgsverdiOverSalgsverdigrense: 'Fritidsbåt med salgsverdi kr 50 000 eller høyere',
    formuesverdiForGaardsbruk: 'Gårdsbruk',
    formuesverdiForInnboLoesoereOgFritidsbaatUnderSalgsverdigrense:
        'Innbo, løsøre og fritidsbåter med salgsverdi under kr 50 000',
    formuesverdiForKjoeretoey: 'Kjøretøy',
    formuesverdiForKontanterIAksjesparekonto: 'Aksjesparekonto - kontantdel',
    formuesverdiForKontanterMvIFondskonto: 'Fondskonto kontant/rentedel',
    formuesverdiForNaeringseiendom: 'Næringseiendom',
    formuesverdiForObligasjon: 'Obligasjoner',
    formuesverdiForPrimaerbolig: 'Primærbolig',
    formuesverdiForRegnskapsbehandletBolig: 'Regnskapsbehandlet bolig',
    formuesverdiForRegnskapsbehandletFritidseiendom: 'Regnskapsbehandlet fritidseiendom',
    formuesverdiForSkogeiendom: 'Skogeiendom',
    formuesverdiForTomt: 'Tomt',
    formuesverdiForUbetingetOpsjonIArbeidsforhold: 'Opsjoner ikke registrert i verdipapirregisteret',
    formuesverdiForUtestaaendeFordringerINaering: 'Utestående fordringer i næring',
    formuesverdiForUtleidFlerboligbygning: 'Utleid flerboligbygning',
    formuesverdiForVarelager: 'Varelager',
    formuesverdiForVirtuellValuta: 'Virtuell valuta / kryptovaluta',
    fortsettelsesforsikring: 'Fortsettelsesforsikring',
    forvaltningskostnaderFinans: 'Forvaltningskostnader finans',
    forvaltningskostnadKnyttetTilAksjesparekonto: 'Forvaltningskostnader for aksjesparekonto',
    forvaltningskostnadKnyttetTilFondskonto: 'Forvaltningskostnader for fondskonto',
    forvaltningskostnadKnyttetTilVerdipapirfond: 'Forvaltningskostnader for verdipapirfond',
    fradragForFagforeningskontingent: 'Fagforeningskontingent',
    fradragForGaverTilFrivilligeOrganisasjoner: 'Gave til frivillige organisasjoner',
    fradragForIndividuellSparingTilPensjon: 'Individuell pensjonsordning (IPS)',
    fradragForPengetilskudd: 'Tilskudd til vitenskapelig forskning',
    fradragForVergegodtgjoerelse: 'Vergegodtgjørelse',
    fradragsberettigetTapPaaKapitalforsikringsavtale: 'Tap av kapitalforsikring',
    fradragsberettigetTapVedRealisasjonAvFastEiendom: 'Tap ved salg av eiendom',
    fradragsberettigetTapVedRealisasjonAvFastEiendomIUtlandet:
        'Tap ved salg eller annen realisasjon av fast eiendom i utlandet',
    fremfoerbartUnderskuddIEnkeltpersonforetak: 'Underskudd i enkeltpersonforetak til framføring senere år',
    gevinstValutalaan: 'Gevinst ved kursendring på valutalån',
    gevinstVedRealisasjonAvAksje: 'Gevinst ved salg av aksjer',
    gevinstVedRealisasjonAvAksjeOgVerdipapirfondAksjedel: 'Gevinst ved salg av aksjer og verdipapirfond aksjedel',
    gevinstVedRealisasjonAvAksjesparekonto: 'Gevinst ved uttak fra aksjesparekonto',
    gevinstVedRealisasjonAvAndelIAksjedelIVerdipapirfond: 'Gevinst ved salg av verdipapirfond - aksjedel',
    gevinstVedRealisasjonAvAndelIRentedelIVerdipapirfond: 'Gevinst ved salg av verdipapirfond - rentedel',
    gevinstVedRealisasjonAvAnnetFinansprodukt: 'Gevinst ved salg av andre finansprodukter',
    gevinstVedRealisasjonAvFastEiendomMv: 'Gevinst ved salg av eiendom',
    gevinstVedRealisasjonAvFastEiendomMvIUtlandet: 'Gevinst ved salg av fast eiendom i utlandet',
    gevinstVedRealisasjonAvObligasjonerSertifikaterMv: 'Gevinst ved salg av obligasjoner',
    gevinstVedRealisasjonAvObligasjonVerdipapirfondRentedelMv:
        'Gevinst ved salg av verdipapirfond rentedel, obligasjoner/sertifikater',
    gevinstVedRealisasjonAvOgUttakFraAksjedelIFondskonto: 'Gevinst ved salg av fondskonto - aksjedel',
    gevinstVedRealisasjonAvOgUttakFraRentedelIFondskonto: 'Gevinst ved salg av fondskonto - rentedel',
    gevinstVedRealisasjonAvVerdipapirfondsandelIKombifondKnyttetTilAksjedel:
        'Gevinst ved salg av verdipapirfond aksjedel kombifond',
    gevinstVedRealisasjonAvVirtuellValuta: 'Gevinst ved salg av virtuell valuta / kryptovaluta',
    gevinstVedSalgAvAndelINOKUS: 'Gevinst ved salg av andeler i NOKUS-selskap',
    gevinstVedSalgAvAndelISDF: 'Gevinst ved salg mv. av andel i selskap med deltakerfastsetting',
    gjeldIInnenlandskeBanker: 'Gjeld til kredittinstitusjoner',
    gjeldINaering: 'Gjeld i næring',
    gjeldIUtlandet: 'Gjeld i utlandet',
    gjeldPaaAnnetFinansprodukt: 'Gjeld på andre finansprodukter',
    gjeldsfradragForKapitalisertFesteavgift: 'Gjeldsfradrag for kapitalisert festeavgift',
    gjeldsreduksjonForFastEiendomIUtlandetUnntattBeskatningINorgeEtterSkatteavtale:
        'Reduksjon av gjeld på grunn av fast eiendom i utlandet',
    gjeldsreduksjonForFastEiendomUtenforSvalbardUnntattBeskatningPaaSvalbard:
        'Reduksjon av gjeld på grunn av fast eiendom utenfor Svalbard',
    gjeldsrentereduksjonForFormueIUtlandetUnntattBeskatningINorgeEtterSkatteavtale:
        'Reduksjon av renter på grunn av fast eiendom i utlandet',
    gjeldsrentereduksjonForFormueUtenforSvalbardUnntattBeskatningPaaSvalbard:
        'Reduksjon av renter på grunn fast eiendom utenfor Svalbard',
    grunnlagForKildeskattPaaPensjonOgUfoereytelser: 'Grunnlag for kildeskatt',
    grunnlagForSkattPaaAlminneligInntektSvalbard: 'Grunnlag for skatt av alminnelig inntekt utenfor lønnstrekkordning',
    grunnlagForSkattPaaNaeringsoverskuddSvalbard: 'Grunnlag for skatt av alminnelig inntekt fra enkeltpersonforetak',
    innskuddIUtlandet: 'Bankinnskudd i utlandet',
    inntektFraGevinstOgTapskonto: 'Inntekt fra gevinst- og tapskonto',
    inntektFraLottEllerPartTilFiskerOgFangstmann: 'Inntekt fra fiske og fangst',
    inntektsfoeringAvNegativSaldo: 'Inntektsføring negativ saldo',
    inntektsfradragAvRentefordelPaaLaanIArbeidsforhold: 'Rentefordel rimelig lån i arbeidsforhold',
    inntektsfradragAvRentefordelPaaLaanIPensjonsforhold: 'Rentefordel rimelig lån i pensjonsforhold',
    inntektsreduksjonVedAvkastningAvEngangserstatning: 'Avkastning knyttet til engangserstatning',
    inntektVedUtleieAvFritidseiendomSomSkattepliktigeHarBrukt: 'Utleie av fritidseiendom',
    introduksjonsstoenad: 'Introduksjonsstønad',
    investeringIOppstartsselskap: 'Fradrag for investering i oppstartsselskap',
    kaarytelseUtenforJordOgSkogbruksvirksomhet: 'Fradrag for kår-/føderådsytelser utenfor næringsvirksomhet',
    kapitalinntektFraSkogbruk: 'Kapitalinntekt skog',
    kapitalkostnadFraSkogbruk: 'Kapitalkostnader skog',
    kontantbeloep: 'Kontanter',
    kvalifiseringsstoenad: 'Kvalifiseringsstønad',
    livrenterIArbeidsforhold: 'Livrenter i arbeidsforhold og fortsettelsesforsikringer',
    livrenterUtenforArbeidsforhold: 'Livrenter utenfor arbeidsforhold',
    loennsinntektMedTrygdeavgiftspliktOmfattetAvLoennstrekkordningen: 'Lønn og naturalytelser med mer - Svalbard',
    loennsinntektTilBarn: 'Lønn til barn som er 12 år eller yngre',
    loennsinntektUtenTrygdeavgiftspliktOmfattetAvLoennstrekkordningen: 'Lønn og naturalytelser med mer - Svalbard',
    minstefradragIBarnepensjon: 'Minstefradrag i egen barnepensjon',
    minstefradragIBarnepensjonTilBarn: 'Minstefradrag i barnepensjon',
    minstefradragIEktefelletillegg: 'Minstefradrag i ektefelletillegg',
    minstefradragIInntekt: 'Minstefradrag i egen inntekt',
    minstefradragIInntektTilBarn: 'Minstefradrag i barns inntekt',
    mottattFesteavgift: 'Mottatt festeavgift',
    naeringsinntektFraKompensasjonsytelseUtbetaltAvNavInnenAnnenNaering:
        'Næringsinntekt av kompensasjon fra NAV - annen næring',
    naeringsinntektFraKompensasjonsytelseUtbetaltAvNavInnenBarnepassIBarnepasserensHjem:
        'Næringsinntekt av kompensasjon fra NAV - barnepass i barnepasserens hjem',
    naeringsinntektFraKompensasjonsytelseUtbetaltAvNavInnenFiskeOgFangst:
        'Næringsinntekt av kompensasjon fra NAV - fiske og fangst',
    negativAlminneligInntektOverfoertFraEktefelle: 'Negativ alminnelig inntekt overført fra ektefelle',
    negativAlminneligInntektOverfoertTilEktefelle: 'Negativ alminnelig inntekt overført til ektefelle',
    negativFormueOverfoertFraEktefelle: 'Negativ formue overført fra ektefelle',
    nettoformue: 'Nettoformue',
    oevrigInntekt: 'Andre inntekter',
    oppjustertTilleggTilAndelIFellesTapVedSalgAvAndelISDF:
        'Oppjustering av andel av tap ved salg mv. av andel i selskap med deltakerfastsetting',
    oppjustertTilleggTilAndelIFellesTilleggIAlminneligInntektFraSDFInnenAnnenNaering:
        'Oppjustering av tillegg i alminnelig inntekt fra selskap med deltakerfastsetting',
    oppjustertTilleggTilGevinstVedRealisasjonAvAksje: 'Oppjustering av gevinst ved salg av aksjer',
    oppjustertTilleggTilGevinstVedRealisasjonAvAksjeOgVerdipapirfondAksjedel:
        'Oppjustering av gevinst ved salg av aksjer og verdipapirfond aksjedel',
    oppjustertTilleggTilGevinstVedRealisasjonAvAksjesparekonto: 'Oppjustering av gevinst ved uttak fra aksjesparekonto',
    oppjustertTilleggTilGevinstVedRealisasjonAvAndelIAksjedelIVerdipapirfond:
        'Oppjustering av gevinst ved salg av verdipapirfond - aksjedel',
    oppjustertTilleggTilGevinstVedRealisasjonAvOgUttakFraAksjedelIFondskonto:
        'Oppjustering av gevinst ved salg av fondskonto - aksjedel',
    oppjustertTilleggTilGevinstVedSalgAvAndelINOKUS: 'Oppjustering av gevinst ved salg av NOKUS-selskap',
    oppjustertTilleggTilGevinstVedSalgAvAndelISDF:
        'Oppjustering av gevinst ved salg mv. av andel i selskap med deltakerfastsetting',
    oppjustertTilleggTilRenteinntektMedEkstrabeskatningForLaanTilSelskap:
        'Oppjustering av renteinntekter fra lån til selskap',
    oppjustertTilleggTilSkattepliktigUtbytteFraAksjeIkkeRegistrertIVerdipapirsentralen:
        'Oppjustering av utbytte på aksjer - ikke i VPS',
    oppjustertTilleggTilSkattepliktigUtbytteFraAksjeINOKUSIkkeRegistrertIVerdipapirsentralen:
        'Oppjustering av utbytte aksjer NOKUS-selskap',
    oppjustertTilleggTilSkattepliktigUtbytteFraAksjeOgVerdipapirfondAksjedel:
        'Oppjustering av utbytte på andeler i verdipapirfond - aksjedel',
    oppjustertTilleggTilTapVedRealisajonAvOgUttakFraAksjedelIFondskonto:
        'Oppjustering av tap ved salg av fondskonto - aksjedel',
    oppjustertTilleggTilTapVedRealisasjonAvAksje: 'Oppjustering av tap ved salg av aksjer',
    oppjustertTilleggTilTapVedRealisasjonAvAksjeOgVerdipapirfondAksjedel:
        'Oppjustering av tap ved salg av aksje- og verdipapirfond, aksjedel',
    oppjustertTilleggTilTapVedRealisasjonAvAksjesparekonto: 'Oppjustering av tap ved salg av aksjesparekonto',
    oppjustertTilleggTilTapVedRealisasjonAvAndelIAksjedelIVerdipapirfond:
        'Oppjustering av tap ved salg av verdipapirfond - aksjedel',
    oppjustertTilleggTilTapVedRealisasjonAvVerdipapirfondsandelIKombifondKnyttetTilAksjedel:
        'Oppjustering av tap ved salg av verdipapirfond aksjedel kombifond',
    oppjustertTilleggTilTapVedSalgAvAndelINOKUS: 'Oppjustering av tap ved salg av andel i NOKUS-selskap',
    oppjustertTilleggTilUtbytteFraAksje: 'Oppjustering av aksjeutbytte',
    oppjustertTilleggTilUtbytteFraVerdipapirfond: 'Oppjustering av utbytte fra verdipapirfond',
    opptjenteRenterFraPrivatUtestaaendeFordring: 'Renteinntekter fra lån til selskap',
    opptjenteRenterFraUtestaaendeFordring: 'Renteinntekter fra andre krav/fordringer',
    overgangsstoenadTilEnsligForelder: 'Overgangsstønad til enslig forsørger',
    overskuddAvEnkeltpersonforetakInnenJordbrukGartneriPelsdyrMv: 'Overskudd fra jordbruk, gartneri og pelsdyrnæring',
    overskuddAvEnkeltpersonforetakInnenReindrift: 'Overskudd fra reindrift',
    overskuddAvEnkeltpersonforetakInnenSkiferproduksjon: 'Overskudd fra skiferproduksjon',
    overskuddAvEnkeltpersonforetakInnenSkogbruk: 'Overskudd fra skogbruk',
    overskuddAvUtgiftsgodtgjoerelseVedSmusstillegg: 'Smusstillegg',
    paaloepteRenterFraAnnenGjeld: 'Renter av annen gjeld',
    paaloepteRenterFraInkassoselskap: 'Rentekostnader til inkassoselskap',
    pensjonFraUtlandetSkattefriINorge: 'Skattefri pensjon fra utlandet',
    pensjonFraUtlandetSkattepliktigINorge: 'Annen pensjon fra utlandet',
    pensjonsinnbetaling: 'Premie til pensjonsordning',
    pensjonsinntektFritattForSkattEtterSkatteavtale: 'Pensjon/trygd fritatt for kildeskatt etter skatteavtale',
    pensjonsinntektIEOESTilsvarendeAlderspensjonEllerAFP:
        'Pensjon fra annen EØS-stat som tilsvarer alderspensjon og AFP i Norge',
    pensjonsinntektOmfattetAvLoennstrekkordningen: 'Pensjoner - Svalbard',
    personinntektFraKompensasjonsytelseUtbetaltAvNavInnenAnnenNaering:
        'Personinntekt av kompensasjon fra NAV - annen næring',
    personinntektFraKompensasjonsytelseUtbetaltAvNavInnenBarnepassIBarnepasserensHjem:
        'Personinntekt av kompensasjon fra NAV - barnepass i barnepasserens hjem',
    personinntektFraKompensasjonsytelseUtbetaltAvNavInnenFiskeOgFangst:
        'Personinntekt av kompensasjon fra NAV - fiske og fangst',
    personinntektFraSDFInnenAnnenNaering: 'Arbeidsgodtgjørelse fra selskap med deltakerfastsetting',
    personinntektFraSDFInnenFiskeEllerBarnepassIBarnepasserensHjem:
        'Arbeidsgodtgjørelse fra selskap med deltakerfastsetting innen fiske eller familiebarnehage',
    personinntektFraSkattefriLottMedTrygdeavgiftspliktForUtenlandskFisker:
        'Personinntekt fra lott innen fiske og fangst',
    positivPersoninntektFraEnkeltpersonforetakPaaSvalbard: 'Positiv personinntekt fra Svalbard',
    premiefond: 'Verdi av premiefond',
    premiefondIndividuellPensjonsavtale: 'Premiefond av individuell pensjonsordning (IPS/IPA)',
    premiefondLivsforsikring: 'Premiefond av livsforsikring',
    premieTilEgenTilleggstrygdForNaeringsdrivende: 'Premie til tilleggstrygd for næringsdrivende',
    reisefradrag: 'Reisefradrag',
    renteinntektAvAnnetFinansprodukt: 'Renter av andre finansprodukter',
    renteinntektAvLivsforsikring: 'Renter av livsforsikring',
    renteinntektAvObligasjon: 'Renteinntekter fra obligasjoner',
    renteinntektAvObligasjonVerdipapirfondRentedelMv:
        'Renteinntekter fra verdipapirfond rentedel, obligasjoner/sertifikater',
    renteinntektAvObligasjonVerdipapirfondRentedelMvIUtlandet:
        'Renteinntekter fra utenlandske verdipapirfond rentedel, obligasjoner/sertifikater',
    renteinntektAvSkadeforsikring: 'Renter av skadeforsikring',
    renteinntektAvVerdipapirfondsandel: 'Renter av verdipapirfond',
    renteinntektMedEkstrabeskatningForLaanTilSelskap: 'Renteinntekter til ekstrabeskatning',
    returAvPremieFraIndividuellPensjonssparing: 'Retur av premie',
    returprovisjonKnyttetTilAksjesparekonto: 'Returprovisjon for aksjesparekonto',
    returprovisjonKnyttetTilFondskonto: 'Returprovisjon for fondskonto',
    returprovisjonKnyttetTilVerdipapirfond: 'Returprovisjon for verdipapirfond',
    saerfradragForEnsligForsoerger: 'Særfradrag for enslige forsørgere',
    saerfradragOverfoertFraBarn: 'Ubenyttet særfradrag overført fra barn',
    saerfradragOverfoertFraEktefelle: 'Særfradrag overført fra ektefelle',
    saerfradragOverfoertTilEktefelle: 'Særfradrag overført til ektefelle',
    saerfradragOverfoertTilForelder: 'Ubenyttet særfradrag overført til foreldre',
    saerskiltFradragForFiskereOgFangstfolk: 'Fradrag for fiske og fangst',
    saerskiltFradragForSjoefolk: 'Særskilt fradrag for sjøfolk',
    saerskiltInntektsfradragIBarnsInntekt: 'Særskilt inntektsfradrag',
    samledeAndreOpptjenteRenter: 'Andre renteinntekter',
    samledeAndrePaaloepteRenter: 'Renter av annen gjeld',
    samledeOpptjenteRenterIInnenlandskeBanker: 'Renter av bankinnskudd',
    samledeOpptjenteRenterIUtenlandskeBanker: 'Renter på bankinnskudd i utenlandsk bank',
    samledePaaloepteRenterPaaGjeldIInnenlandskeBanker: 'Renter av gjeld',
    samledePaaloepteRenterPaaGjeldIUtlandet: 'Gjeldsrenter i utlandet',
    samledeUfoererenterOgLivrenter: 'Uførerenter og livrenter i og utenfor arbeidsforhold',
    samletAndelAvFellesgjeldIBoligselskapEllerBoligsameie: 'Gjeld i boligselskap/-sameie',
    samletAndelAvFradragsberettigetFelleskostnadForBoligselskapEllerBoligsameie:
        'Andel av kostnader i boligselskap/-sameie',
    samletAndelAvInntektIBoligselskapEllerBoligsameie: 'Andel av inntekter i boligselskap/-sameie',
    samletAnnenGjeld: 'Annen gjeld',
    samletAnnenPensjonMedTrekkpliktEksklusiveEktefelletillegg: 'Andre pensjoner',
    samletAnnenPensjonUtenTrekkplikt: 'Andre pensjoner uten skattetrekk',
    samletAvkastningAvKapitalforsikringsavtale: 'Avkastning/gevinst av kapitalforsikring',
    samletAvtalefestetPensjon: 'Avtalefestet pensjon (AFP)',
    samletBarnepensjonOgLivrente: 'Barnepensjon og livrente',
    samletBarnepensjonOgLivrenteTilBarn: 'Barnepensjon og livrente til dine barn som er 16 år eller yngre',
    samletFormuesverdiAvPrivatUtestaaendeFordring: 'Lån til selskap',
    samletFormuesverdiForAndelAnnenFormueIBoligselskapEllerBoligsameie: 'Andel av formue i boligselskap/-sameie',
    samletFormuesverdiForFastEiendomIUtlandet: 'Fast eiendom i utlandet',
    samletFormuesverdiForOevrigFormue: 'Annen formue',
    samletFormuesverdiForOevrigFormueIUtlandet: 'Annen formue i utlandet',
    samletFormuesverdiForSekundaerbolig: 'Sekundærbolig',
    samletFormuesverdiForSelveidFritidseiendomEllerAndelIFritidsboligselskap: 'Fritidsbolig',
    samletFradragsberettigetKostnadTilknyttetArbeidMv: 'Faktiske kostnader',
    samletFradragsberettigetUnderskuddVedUtleieAvFastEiendom: 'Underskudd ved utleie',
    samletFremfoerbartUnderskuddFraTidligereAar: 'Fremført underskudd fra tidligere år',
    samletGjeld: 'Sum gjeld',
    samletGjenkjoepsverdiForLivsforsikring: 'Gjenkjøpsverdi av forsikringsavtale',
    samletGrunnlagForInntektsskattTilKommuneOgFylkeskommuneStatsskattOgFellesskatt: 'Sum grunnlag for inntektsskatt',
    samletInnskuddIInnenlandskeBanker: 'Bankinnskudd',
    samletInntektSomGirRettTilSaerskiltFradragForSjoefolk: 'Lønn til sjøfolk',
    samletLoennsinntektMedTrygdeavgiftspliktOgMedTrekkplikt: 'Lønn og naturalytelser med mer',
    samletLoennsinntektUtenTrygdeavgiftspliktOgMedTrekkplikt: 'Lønn og naturalytelser med mer',
    samletLoennsinntektUtenTrygdeavgiftspliktOgUtenTrekkplikt: 'Lønn og naturalytelser med mer',
    samletMerkostnadVedArbeidsoppholdUtenforHjem: 'Merkostnader ved arbeidsopphold utenfor hjemmet',
    samletOverskuddAvEnkeltpersonforetakInnenAnnenNaering: 'Overskudd fra annen næring',
    samletOverskuddAvEnkeltpersonforetakInnenFamiliebarnehageEllerDagmammaIEgetHjem:
        'Overskudd fra barnepass i barnepasserens hjem',
    samletOverskuddAvEnkeltpersonforetakInnenFiskeOgFangst: 'Overskudd fra fiske og fangst',
    samletOverskuddAvSDFInnenAnnenNaering: 'Inntekt fra selskap med deltakerfastsetting innen annen næring',
    samletOverskuddAvSDFInnenFiskeEllerFamiliebarnehage:
        'Inntekt fra selskap med deltakerfastsetting innen fiske og fangst eller barnepass i barnepasserens hjem',
    samletOverskuddPaaUtgiftsgodtgjoerelse: 'Overskudd fra utgiftsgodtgjørelse',
    samletPensjonFraFolketrygden: 'Alderspensjon fra folketrygden',
    samletPersoninntektFraEnkeltpersonforetakInnenFamiliebarnehageEllerDagmammaIEgetHjem: 'Personinntekt fra barnepass',
    samletPersoninntektFraEnkeltpersonforetakInnenFiskeOgFangst: 'Personinntekt fra fiske og fangst',
    samletSaerfradrag: 'Særfradrag',
    samletSaerfradragForStoreSykdomsutgifter: 'Særfradrag for store sykdomskostnader/lettere nedsatt ervervsevne',
    samletSaerskiltFradragForJordbrukReindriftOgSkiferproduksjon: 'Særskilt fradrag (jordbruk, reindrift og skifer)',
    samletSkattefriDelAvFormue: 'Engangserstatning barn under 22 år',
    samletSkattepliktigOverskuddFraUtleieAvFastEiendom: 'Utleie av fast eiendom',
    samletSkattepliktigOverskuddFraUtleieAvFastEiendomIUtlandet: 'Utleie av fast eiendom i utlandet',
    samletUfoeretrygdFraFolketrygdenEksklusiveEktefelletillegg: 'Uføretrygd fra folketrygden',
    samletUfoereytelseFraAndreEnnFolketrygden: 'Uføreytelser fra andre enn folketrygden',
    samletUnderskuddAvSDF: 'Andel av underskudd fra selskap med deltakerfastsetting',
    samletUnderskuddINaeringsvirksomhet: 'Underskudd i næringsvirksomhet',
    skattefriLoennsinntektMedTrygdeavgiftspliktOgMedTrekkplikt: 'Skattefri inntekt, trygdeavgiftspliktig',
    skattepliktigAvkastningEllerKundeutbytte: 'Skattepliktig avkastning kundeutbytte mv.',
    skattepliktigEtterloennOgEtterpensjon: 'Skattepliktig etterlønn og etterpensjon',
    skattepliktigUtbytteFraAksjeIkkeRegistrertIVerdipapirsentralen: 'Utbytte på aksjer - ikke i VPS',
    skattepliktigUtbytteFraAksjeINOKUSIkkeRegistrertIVerdipapirsentralen: 'Utbytte på aksjer NOKUS-selskap',
    skattepliktigUtbytteFraAksjeOgVerdipapirfondAksjedel: 'Utbytte på andeler i verdipapirfond - aksjedel',
    skyldigRestskatt: 'Skyldig restskatt',
    skyldigUnderholdsbidrag: 'Skyldig underholdsbidrag',
    slitertillegg: 'Slitertillegg',
    standardfradrag: 'Standardfradrag for utenlandske arbeidstakere på skip eller sokkel',
    styrehonorarFraNorskSelskapTilSkattepliktigBosattIUtlandet:
        'Styrehonorar fra norsk selskap til person bosatt i utlandet',
    sumFradragIAlminneligInntekt: 'Sum fradrag',
    sumGjeldsreduksjon: 'Reduksjon av gjeld på grunn av verdsettingsrabatt',
    sumInntekterIAlminneligInntektFoerFordelingsfradrag: 'Sum inntekter',
};
