export default {
    'form.begrunnelse': 'Begrunnelse',
    'form.delerBolig': 'Deler søker bolig med noen over 18 år?',
    'form.erEPSUførFlyktning': 'Er ektefelle/samboer ufør flyktning?',
    'form.epsFnr': 'Ektefelle/samboers fødelsnummer',
    'form.harSøkerEPS': 'Har søker ektefelle eller samboer?',
    'form.beskrivelse': 'Unngå personsensitive opplysninger',
    'form.fjern.bosituasjon': 'Slett',
    'form.ny.bosituasjon': 'Ny periode for opplysning',
    'form.fraOgMed': 'Fra og med',
    'form.tilOgMed': 'Til og med',

    'eksisterende.vedtakinfo.tittel': 'Eksisterende vedtaksinformasjon',
    'eksisterende.vedtakinfo.søkerBorMed': 'Søker bor med',
    'eksisterende.vedtakinfo.eps': 'Ektefelle eller samboer',
    'eksisterende.vedtakinfo.over18år': 'Voksne over 18 år',
    'eksisterende.vedtakinfo.enslig': 'Enslig',
    'eksisterende.vedtakinfo.mottarSU': 'Er ektefelle eller samboer ufør flyktning?',
    'eksisterende.vedtakinfo.sats': 'Sats',
    'eksisterende.vedtakinfo.ja': 'Ja',
    'eksisterende.vedtakinfo.nei': 'Nei',
};
