export default {
    'input.inntekt.forventetInntekt': 'Forventet inntekt (arbeidsinntekt)',
    'input.mottarPensjon.label': 'Har du tjenestepensjon og/eller pensjonssparing?',
    'input.pensjonsOrdning.label': 'Pensjonsgiver',
    'input.pensjonsBeløp.label': 'Beløp',
    'input.harMottattSosialstønad.label': 'Har du mottatt sosialstønad i løpet av de siste tre månedene?',
    'input.sosialStønadBeløp.label': 'Beløp i kroner for alle tre månedene',
    'input.trygdeytelserIUtlandet.label': 'Har du trygdeytelser i utlandet?',
    'input.trygdeytelserIUtlandetBeløp.label': 'Beløp i kroner',
    'input.trygdeytelserIUtlandetType.label': 'Hvilke ytelser?',
    'input.trygdeytelserIUtlandetFraHvem.label': 'Hvem gir disse ytelsene?',
    'input.tjenerPengerIUtlandet.label': 'Tjener du penger i utlandet?',
    'input.tjenerPengerIUtlandetBeløp.label': 'Beløp i kroner',
    'input.andreYtelserINAV.label': 'Har du andre ytelser i NAV?',
    'input.andreYtelserINavYtelse.label': 'Hvilke ytelser?',
    'input.andreYtelserINavBeløp.label': 'Beløp i kroner',
    'input.søktAndreYtelserIkkeBehandlet.label': 'Har du søkt om andre trygdeytelser som ikke er behandlet?',
    'input.søktAndreYtelserIkkeBehandletBegrunnelse.label': 'Hvilke? ',
};
