export default {
    'forhåndsvarsel.sendt': 'Forhåndsvarsel sendt',
    'forhåndsvarsel.tittel': 'Forhåndsvarsel',
    'forhåndsvarsel.neste.sendOgNaviger': 'Send og fortsett til saksoversikt',
    'forhåndsvarsel.fortsettSenere': 'Fortsett senere',
    'forhåndsvarsel.skalSendes': 'Skal det sendes forhåndsvarsel?',
    'forhåndsvarsel.skalSende.ja': 'Ja',
    'forhåndsvarsel.skalSende.nei': 'Nei',
    'forhåndsvarsel.fritekst.label': 'Fritekst til forhåndsvarsel',
    'forhåndsvarsel.dokumenterAlert.ingenForhåndsvarsel': 'Ingen sendte forhåndsvarsel',
    'forhåndsvarsel.knapp.leggTilMottaker': 'Legg til mottaker',
    'forhåndsvarsel.knapp.lukkMottaker': 'Lukk mottaker',
    'forhåndsvarsel.knapp.visMottaker': 'Vis mottaker',
    'forhåndsvarsel.feilmelding.kanIkkeHenteMottaker': 'Kan ikke hente mottaker',
};
