export default {
    'panel.tittel.uførevedtak': 'Uførevedtak',
    'input.uførevedtak.label': 'Har du uførevedtak?',

    'panel.tittel.flyktningstatus': 'Flyktningstatus',
    'input.flyktning.label': 'Er du registrert som flyktning?',
    'input.norsk.statsborger.label': 'Er du norsk statsborger?',
    'input.oppholdstillatelse.label': 'Har du oppholdstillatelse i Norge?',
    'input.hvilken.oppholdstillatelse.label': 'Hvilken type oppholdstillatelse har du?',
    'input.permanent.oppholdstillatelse.label': 'Permanent',
    'input.midlertidig.oppholdstillatelse.label': 'Midlertidig',
    'input.midlertidig.oppholdstillatelse.opphører.label':
        'Er det mindre enn tre måneder til oppholdstillatelsen opphører?',
    'input.oppholdtillatelse.forlengelse.label': 'Har du søkt forlengelse?',
    'input.statsborger.andre.land.label': 'Har du statsborgerskap i andre land enn Norge?',
    'input.statsborger.andre.land.fritekst.label': 'Hvilke land?',

    'panel.tittel.boOgOpphold': 'Bo og opphold i Norge',
    'input.opphold-i-norge.label': 'Bor og oppholder i Norge?',
    'input.folkereg-adresse.label': 'Bor på folkereg adresse?',
    'input.delerBoligMedPersonOver18.label': 'Deler du bolig med noen over 18 år?',
    'input.delerBoligMed.label': 'Hvem deler du bolig med?',
    'input.delerBoligMedEktemakeEllerSamboer.label': 'Ektemake eller samboer',
    'input.delerBoligMedBarnOver18.label': 'Voksne barn',
    'input.delerBoligMedAndreVoksne.label': 'Andre voksne',
    'input.ektemakeEllerSamboerUnder67År.label': 'Er ektemake eller samboer under 67 år?',
    'input.ektemakeEllerSamboerUførFlyktning.label': 'Er ektemake eller samboer ufør flyktning?',

    'panel.tittel.dinFormue': 'Din formue',
    'input.harFormue.label': 'Har du formue?',
    'input.oppgiBeløp.label': 'Oppgi beløp på formue',
    'input.eierDuBolig.label': 'Eier du bolig?',
    'input.depositumskonto.label': 'Har du en depositumskonto?',

    'panel.tittel.dinInntekt': 'Din inntekt',
    'input.harInntekt.label': 'Har du inntekt?',
    'input.inntekt.inntektBeløp': 'Oppgi beløp på inntekt',
    'input.mottarPensjon.label': 'Mottar du pensjon?',
    'input.pensjonsOrdning.label': 'Fra hvilken ordning mottar du pensjon?',
    'input.pensjonsBeløp.label': 'Brutto beløp per år',
    'input.harMottattSosialstønad.label': 'Har du mottatt sosialstønad i løpet av de siste tre månedene?',

    'panel.tittel.reiseTilUtlandet': 'Reise til utlandet',
    'input.harReistSiste90.label': 'Har du reist til utlandet de siste 90 dager?',
    'input.skalReiseNeste12.label': 'Har du planer om å reise til utlandet i de neste 12 månedene?',
    'input.utreisedato': 'Utreisedato',
    'input.innreisedato': 'innreisedato',

    'panel.tittel.kontakt': 'kontakt',
};
