name: Deploy alerts to NAIS
on:
    push:
        branches:
            - master
        paths:
            - 'alerts.yml'
            - '.github/workflows/alerts-deploy.yml'

permissions: { }

jobs:
    apply-alerts:
        name: Apply alerts to cluster
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v7
            - name: deploy to dev
              uses: nais/deploy/actions/deploy@v2
              env:
                  CLUSTER: dev-gcp
                  RESOURCE: alerts.yml
                  VAR: SLACK_ALERTS_CHANNEL=#su_alerts_dev,LOGS_URL_LOKI=https://grafana.nav.cloud.nais.io/goto/efq0y6eulatc0c?orgId=1

            - name: deploy to prod
              uses: nais/deploy/actions/deploy@v2
              env:
                  CLUSTER: prod-gcp
                  RESOURCE: alerts.yml
                  VAR: SLACK_ALERTS_CHANNEL=#su_alerts,LOGS_URL_LOKI=https://grafana.nav.cloud.nais.io/goto/ffq0y43v6ll34a?orgId=1
