name: build-push-deploy-to-dev.yml

on:
    push:
      branches:
        - '**'
    workflow_dispatch:

permissions: { }

jobs:
    build-push-docker-image:
        name: build-push-docker-image
        runs-on: ubuntu-latest
        outputs:
            image: ${{ steps.docker-build-push.outputs.image }}
        permissions:
            packages: 'write'
            contents: 'read'
            id-token: 'write'
        steps:
            - uses: actions/checkout@v4
              with:
                  persist-credentials: false
            - uses: actions/setup-node@v4.4.0
              with:
                  node-version: '20.x'
            - name: install-deps-client-and-server
              run: npm ci
            - name: lint-and-typecheck
              run: npm run lint-and-typecheck
            - name: build-client
              run: npm run build
            - name: build-server
              working-directory: server
              run: npm run build
            - name: create-sentry-release
              if: (github.ref == 'refs/heads/master') || (github.event_name == 'workflow_dispatch')
              run: npm run sentry-release
              env:
                  SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
            - name: docker-login
              if: (github.ref == 'refs/heads/master') || (github.event_name == 'workflow_dispatch')
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and publish Docker image
              if: (github.ref == 'refs/heads/master') || (github.event_name == 'workflow_dispatch')
              uses: nais/docker-build-push@v0
              id: docker-build-push
              with:
                docker_context: .
                team: supstonad
                identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
                project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
                salsa: false
                image_suffix: ${{ github.workflow }}
                tag: ${{ env.GITHUB_REF_SLUG }}

    deploy-to-dev-fss:
        if: (github.ref == 'refs/heads/master') || (github.event_name == 'workflow_dispatch')
        name: deploy-to-dev-fss
        permissions:
          contents: read
          id-token: write
        needs: build-push-docker-image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: nais/deploy/actions/deploy@v2
              env:
                  CLUSTER: dev-fss
                  RESOURCE: .nais/dev.yaml
                  VAR: image=${{ needs.build-push-docker-image.outputs.image }}

    generate-draft-release:
        if: (github.ref == 'refs/heads/master')
        name: Generate/update draft release
        runs-on: ubuntu-latest
        permissions:
            contents: 'write' # needed to create/edit releases
            pull-requests: 'write' # needed to add labels to pull requests
        steps:
            # Drafts your next Release notes as Pull Requests are merged into "master"
            - uses: release-drafter/release-drafter@v6
              #with:
              # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
              # config-name: my-config.yml
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
