name: Lag release ved ny tag

on:
    push:
        tags:
            - 'v*'

jobs:
    create_release:
        name: Create release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Create a GitHub release
              uses: 'marvinpinto/action-automatic-releases@latest'
              with:
                  repo_token: '${{ secrets.GITHUB_TOKEN }}'
                  prerelease: false
