name: Generering av prerelease

on:
    push:
        branches:
            - tag-test # Dette skal gjøres på master

jobs:
    generate-pre-release:
        name: Generate pre-release
        runs-on: ubuntu-latest
        steps:
            - uses: 'marvinpinto/action-automatic-releases@latest'
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  automatic_release_tag: 'latest'
                  prerelease: true
                  title: Development build
